name: Windows

on:
  push:
    branches: [ master, dev, physics, github-actions ]
  pull_request:
    branches: [ master, dev, physics, github-actions ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: submodules
      run: git submodule update --init --recursive -j $(getconf _NPROCESSORS_ONLN)

    - name: Setup premake
      uses: abel0b/setup-premake@v1

    - name: premake
      run: premake5 gmake2
    
    - name: compile-release
      run: premake5 --version


    
      
      
      
